version: '3.7'
services:
  bigote-fetcher:
    container_name: bigote-fetcher
    build:
      context: .
      dockerfile: dockers/bigote-fetcher/Dockerfile
    tty: true 
    restart: always
    volumes: 
      - ./app:/app
    depends_on:
      - bigote-pg

  bigote-pg:
    image: postgres:12.2-alpine
    container_name: bigote-pg
    tty: true
    restart: always
    volumes:
      - bigote-pg-data:/var/lib/postgresql/data
      - ./dockers/bigote-pg/initdb:/docker-entrypoint-initdb.d
    stdin_open: true
    ports:
      - "34321:5432"
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
      POSTGRES_PASSWORD: postgres

volumes:
  bigote-pg-data:

